name: California_houses
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - geopandas
  - folium
  - mapclassify
  - statsmodels
  - joblib
  - pillow
  - pyyaml
  - requests
  - pip
  - pip:
      - streamlit
      - pydeck
      - pyarrow
      - altair
      - watchdog
      - contextily
      - xyzservices