name: California_houses
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - geopandas
  - joblib
  - pip
  - pip:
      - streamlit
      - pydeck
      - pyarrow